### ISSUE TITLE
Create cookiecutter templates

### ISSUE THREAD

**Issue by leonardovida** [UtrechtUniversity/rse-project-templates#4]
As mentioned by @MartineDeVos, an interesting possibility might be creating [cookiecutter](https://github.com/cookiecutter/cookiecutter) templates for Python projects and similar for R projects. 

### Concerning Python
Cookiecutter templates might be divided in:
- For those who use [pipenv](https://github.com/pypa/pipenv): [https://github.com/elgertam/cookiecutter-pipenv](https://github.com/elgertam/cookiecutter-pipenv)
- For those who use [poetry](https://python-poetry.org/): [https://github.com/wboxx1/cookiecutter-pypackage-poetry](https://github.com/wboxx1/cookiecutter-pypackage-poetry)
- And a basic one for projects that are outside the scope of the above (e.g. basic jupyter notebooks) or for those who don't use anything (but actually **should**) 😄 

### Concerning R
Here @J535D165 might suggest something better, but I know:
- [rrtools](https://github.com/benmarwick/rrtools)
- [starters](https://github.com/lockedata/starters)

**Comment by jelletreep** [comment]
Time flies, would be nice to go into this again sometime soon!

E.g. I would love a python project template with poetry, GitHub actions for pylint en pytest?
Starting from here? [https://github.com/fpgmaas/cookiecutter-poetry](https://github.com/fpgmaas/cookiecutter-poetry)

Any ideas about one or multiple python project templates and what should be included?
